### ISSUE TITLE
Morning session: Peer-to-peer code review 7/1/2022

### ISSUE THREAD

**Issue by Alzubair98** [DavyKn/Awesome_Books2#3]
your code look super amazing 💯 💯 

but i think you can make it better by increase the size of the (copywrite) word  try use h or just increase the font size 👍

**Comment by lucas-crodrigues** [comment]
first of all congratulations on your code, it looks great, and there are no bugs 🔥 
As an optional suggestion, I'd suggest you add some form of validation for when a book is added or clear the form
